package org.w3c.utils.css.enums;

import org.w3c.utils.css.help.AnyUtils;

/**
 * Created by Home on 22.08.2016.
 */
public enum Properties
{
    ALIGN, // ALIGN_CONTENT, ALIGN_ITEMS,
    ANIMATION, // ANIMATION_NAME, ANIMATION_DURATION, ANIMATION_DELAY, ANIMATION_DIRECTION, ...
    BACKGROUND, // BACKGROUND_IMAGE, BACKGROUND_POSITION, BACKGROUND_REPEAT, BACKGROUND_SIZE, ...
    BORDER, // BORDER_STYLE, BORDER_WIDTH, BORDER_COLOR, BORDER_RADIUS, BORDER_IMAGE
    BOTTOM,
    BOX_SIZING,
    CARET_COLOR,
    CLEAR,
    CLIP,
    COLOR,
    CONTENT,
    COUNTER, // COUNTER_INCREMENT, COUNTER_RESET
    CURSOR,
    DISPLAY,
    FLOAT,
    FONT,
    HEIGHT,
    IMAGE_ORIENTATION,
    LEFT,
    LETTER_SPACING,
    LINE_HEIGHT,
    LIST, // LIST-STYLE
    MARGIN,
    MARQUEE,
    MASK, // MASK_...
    MAX_WIDTH,
    MAX_HEIGHT,
    MIN_WIDTH,
    MIN_HEIGHT,
    MIX_BLEND_MODE,
    OUTLINE, // OUTLINE_COLOR, OUTLINE_OFFSET, OUTLINE_STYLE, OUTLINE_WIDTH
    OVERFLOW,
    OBJECT_FIT,
    OBJECT_POSITION,
    ORPHANS,
    OPACITY,
    PADDING,
    PAGE,
    POSITION,
    RESIZE,
    RIGHT,
    SHAPE, // SHAPE_IMAGE_THRESHOLD, SHAPE_OUTSIDE, SHAPE_MARGIN
    SIZE,
    TEXT, // TEXT_ALIGN, TEXT_DECORATION, TEXT_INDENT, TEXT_TRANSFORM, TEXT_OVERFLOW
    TABLE_LAYOUT,
    TRANSFORM,
    TRANSITION,
    TOP,
    VERTICAL_ALIGN,
    VISIBILITY,
    WHITE_SPACE,
    WINDOWS,
    WIDTH,
    WORD, // WORD_BREAK, WORD_SPACING, WORD_WRAP
    WRITING_MODE,
    ZOOM,
    Z_INDEX;

    @Override
    public String toString()
    {
        return AnyUtils.cssEnum2cssName(this);
    }
}
